#!/bin/sh

#
# This script is a part of japanese-otf-uptex.
#

# setting for ovp2ovf & uppltotf
. ./umakeotf_pre

if test ! -d tfm; then
mkdir tfm
fi


echo "making tfm for jis2004 ..."
for series in nml exp
do
for face in minr gothr minb gothb mgothr
do
$UPPLTOTF -kanji=uptex basepl/ubase-h.pl tfm/up${series}${face}n-h.tfm
$UPPLTOTF -kanji=uptex basepl/ubase-v.pl tfm/up${series}${face}n-v.tfm
done
done
#for extra fonts
for series in nml exp
do
for face in gotheb minl
do
$UPPLTOTF -kanji=uptex basepl/ubase-h.pl tfm/up${series}${face}n-h.tfm
$UPPLTOTF -kanji=uptex basepl/ubase-v.pl tfm/up${series}${face}n-v.tfm
done
done


echo "making tfm for burasage & jis2004 ..."
for series in nml exp
do
for face in minr gothr minb gothb mgothr
do
$UPPLTOTF -kanji=uptex basepl/ubrsg-h.pl tfm/upbrsg${series}${face}n-h.tfm
$UPPLTOTF -kanji=uptex basepl/ubrsg-v.pl tfm/upbrsg${series}${face}n-v.tfm
done
done
#for extra fonts
for series in nml exp
do
for face in gotheb minl
do
$UPPLTOTF -kanji=uptex basepl/ubrsg-h.pl tfm/upbrsg${series}${face}n-h.tfm
$UPPLTOTF -kanji=uptex basepl/ubrsg-v.pl tfm/upbrsg${series}${face}n-v.tfm
done
done


echo "making vf for jis2004 ..."
for face in minr gothr minb gothb mgothr
do
./umkjvf -ucs -sp 1 -omitfw -cq     -svs script/svs_list_j.txt -ccmb upnml${face}n-h uph${face}n-h
./umkjvf -ucs -sp 1 -omitfw -cm -cp -svs script/svs_list_j.txt -ccmb upnml${face}n-v uph${face}n-v
done
#extra fonts
for face in gotheb minl
do
./umkjvf -ucs -sp 1 -omitfw -cq     -svs script/svs_list_j.txt -ccmb upnml${face}n-h uph${face}n-h
./umkjvf -ucs -sp 1 -omitfw -cm -cp -svs script/svs_list_j.txt -ccmb upnml${face}n-v uph${face}n-v
done

for face in minr gothr minb gothb mgothr
do
./umkjvf -ucs -sp 1 -omitfw -cq     -expert upexp${face}n-h  uph${face}n-h cidj${face}
./umkjvf -ucs -sp 1 -omitfw -cm -cp -expert upexp${face}n-v  uph${face}n-v cidj${face}
done
#extra fonts
for face in gotheb minl
do
./umkjvf -ucs -sp 1 -omitfw -cq     -expert upexp${face}n-h  uph${face}n-h cidj${face}
./umkjvf -ucs -sp 1 -omitfw -cm -cp -expert upexp${face}n-v  uph${face}n-v cidj${face}
done


echo "making vf for burasage & jis2004 ..."
for face in minr gothr minb gothb mgothr
do
./umkjvf -ucs -sp 1 -sage -omitfw -cq     upbrsgnml${face}n-h uph${face}n-h
./umkjvf -ucs -sp 1 -sage -omitfw -cm -cp upbrsgnml${face}n-v uph${face}n-v
done
#extra fonts
for face in gotheb minl
do
./umkjvf -ucs -sp 1 -sage -omitfw -cq     upbrsgnml${face}n-h uph${face}n-h
./umkjvf -ucs -sp 1 -sage -omitfw -cm -cp upbrsgnml${face}n-v uph${face}n-v
done

for face in minr gothr minb gothb mgothr
do
./umkjvf -ucs -sp 1 -sage -omitfw -cq     -expert upbrsgexp${face}n-h uph${face}n-h cidj${face}
./umkjvf -ucs -sp 1 -sage -omitfw -cm -cp -expert upbrsgexp${face}n-v uph${face}n-v cidj${face}
done
#extra fonts
for face in gotheb minl
do
./umkjvf -ucs -sp 1 -sage -omitfw -cq     -expert upbrsgexp${face}n-h uph${face}n-h cidj${face}
./umkjvf -ucs -sp 1 -sage -omitfw -cm -cp -expert upbrsgexp${face}n-v uph${face}n-v cidj${face}
done


echo "finishing ..."
if test ! -d vf; then
mkdir vf
fi
mv *.vf vf/
mv *.tfm tfm/
