#!/bin/sh
echo "making tfm ..."
perl script/mktfm.pl
ppltotf basepl/base-h.pl tfm/nmlminr-h.tfm
ppltotf basepl/base-v.pl tfm/nmlminr-v.tfm
ppltotf basepl/base-h.pl tfm/nmlgothr-h.tfm
ppltotf basepl/base-v.pl tfm/nmlgothr-v.tfm
ppltotf basepl/base-h.pl tfm/nmlminb-h.tfm
ppltotf basepl/base-v.pl tfm/nmlminb-v.tfm
ppltotf basepl/base-h.pl tfm/nmlgothb-h.tfm
ppltotf basepl/base-v.pl tfm/nmlgothb-v.tfm
ppltotf basepl/base-h.pl tfm/nmlmgothr-h.tfm
ppltotf basepl/base-v.pl tfm/nmlmgothr-v.tfm
ppltotf basepl/base-h.pl tfm/expminr-h.tfm
ppltotf basepl/base-v.pl tfm/expminr-v.tfm
ppltotf basepl/base-h.pl tfm/expgothr-h.tfm
ppltotf basepl/base-v.pl tfm/expgothr-v.tfm
ppltotf basepl/base-h.pl tfm/expminb-h.tfm
ppltotf basepl/base-v.pl tfm/expminb-v.tfm
ppltotf basepl/base-h.pl tfm/expgothb-h.tfm
ppltotf basepl/base-v.pl tfm/expgothb-v.tfm
ppltotf basepl/base-h.pl tfm/expmgothr-h.tfm
ppltotf basepl/base-v.pl tfm/expmgothr-v.tfm
ppltotf basepl/base-v.pl tfm/rubyminr-v.tfm
ppltotf basepl/base-h.pl tfm/rubyminr-h.tfm
ppltotf basepl/base-h.pl tfm/rubygothr-h.tfm
ppltotf basepl/base-v.pl tfm/rubygothr-v.tfm
ppltotf basepl/base-v.pl tfm/rubyminb-v.tfm
ppltotf basepl/base-h.pl tfm/rubyminb-h.tfm
ppltotf basepl/base-h.pl tfm/rubygothb-h.tfm
ppltotf basepl/base-v.pl tfm/rubygothb-v.tfm
ppltotf basepl/base-h.pl tfm/rubymgothr-h.tfm
ppltotf basepl/base-v.pl tfm/rubymgothr-v.tfm
ppltotf basepl/base0-h.pl tfm/cidjmr0-h.tfm
ppltotf basepl/base2-h.pl tfm/cidjmr2-h.tfm
ppltotf basepl/base2-v.pl tfm/cidjmr2-v.tfm
ppltotf basepl/base3-v.pl tfm/cidjmr3-v.tfm
ppltotf basepl/base0-h.pl tfm/cidjgr0-h.tfm
ppltotf basepl/base2-h.pl tfm/cidjgr2-h.tfm
ppltotf basepl/base2-v.pl tfm/cidjgr2-v.tfm
ppltotf basepl/base3-v.pl tfm/cidjgr3-v.tfm
ppltotf basepl/base0-h.pl tfm/cidjmb0-h.tfm
ppltotf basepl/base2-h.pl tfm/cidjmb2-h.tfm
ppltotf basepl/base2-v.pl tfm/cidjmb2-v.tfm
ppltotf basepl/base3-v.pl tfm/cidjmb3-v.tfm
ppltotf basepl/base0-h.pl tfm/cidjgb0-h.tfm
ppltotf basepl/base2-h.pl tfm/cidjgb2-h.tfm
ppltotf basepl/base2-v.pl tfm/cidjgb2-v.tfm
ppltotf basepl/base3-v.pl tfm/cidjgb3-v.tfm
ppltotf basepl/base0-h.pl tfm/cidjmgr0-h.tfm
ppltotf basepl/base2-h.pl tfm/cidjmgr2-h.tfm
ppltotf basepl/base2-v.pl tfm/cidjmgr2-v.tfm
ppltotf basepl/base3-v.pl tfm/cidjmgr3-v.tfm
#for extra fonts
ppltotf basepl/base-h.pl tfm/nmlgotheb-h.tfm
ppltotf basepl/base-v.pl tfm/nmlgotheb-v.tfm
ppltotf basepl/base-h.pl tfm/expgotheb-h.tfm
ppltotf basepl/base-v.pl tfm/expgotheb-v.tfm
ppltotf basepl/base-v.pl tfm/rubygotheb-v.tfm
ppltotf basepl/base-h.pl tfm/rubygotheb-h.tfm
ppltotf basepl/base0-h.pl tfm/cidjge0-h.tfm
ppltotf basepl/base2-h.pl tfm/cidjge2-h.tfm
ppltotf basepl/base2-v.pl tfm/cidjge2-v.tfm
ppltotf basepl/base3-v.pl tfm/cidjge3-v.tfm
ppltotf basepl/base-h.pl tfm/nmlminl-h.tfm
ppltotf basepl/base-v.pl tfm/nmlminl-v.tfm
ppltotf basepl/base-h.pl tfm/expminl-h.tfm
ppltotf basepl/base-v.pl tfm/expminl-v.tfm
ppltotf basepl/base-v.pl tfm/rubyminl-v.tfm
ppltotf basepl/base-h.pl tfm/rubyminl-h.tfm
ppltotf basepl/base0-h.pl tfm/cidjml0-h.tfm
ppltotf basepl/base2-h.pl tfm/cidjml2-h.tfm
ppltotf basepl/base2-v.pl tfm/cidjml2-v.tfm
ppltotf basepl/base3-v.pl tfm/cidjml3-v.tfm
echo "making vf (wait a while)..."
perl script/mkutfvf.pl
echo "vf for utf finished. making vf for cid..."
perl script/mkcidvf.pl
perl script/mkmlcidvf.pl
echo "vf for cid finished. making vf for alt. utf..."
perl script/mkaltutfvf.pl
./mkjvf nmlminr-h hminr-h
./mkjvf -cm -cp nmlminr-v hminr-v
./mkjvf nmlgothr-h hgothr-h
./mkjvf -cm -cp nmlgothr-v hgothr-v
./mkjvf nmlminb-h hminb-h
./mkjvf -cm -cp nmlminb-v hminb-v
./mkjvf nmlgothb-h hgothb-h
./mkjvf -cm -cp nmlgothb-v hgothb-v
./mkjvf nmlmgothr-h hmgothr-h
./mkjvf -cm -cp nmlmgothr-v hmgothr-v
#extra fonts
./mkjvf nmlgotheb-h hgotheb-h
./mkjvf -cm -cp nmlgotheb-v hgotheb-v
./mkjvf nmlminl-h hminl-h
./mkjvf -cm -cp nmlminl-v hminl-v
echo "making alt. kana ..."
./mkjvf -expert expminr-h hminr-h cidjminr
./mkjvf -cm -cp -expert expminr-v hminr-v cidjminr
./mkjvf -expert expgothr-h hgothr-h cidjgothr
./mkjvf -cm -cp -expert expgothr-v hgothr-v cidjgothr
./mkjvf -expert expminb-h hminb-h cidjminb
./mkjvf -cm -cp -expert expminb-v hminb-v cidjminb
./mkjvf -expert expgothb-h hgothb-h cidjgothb
./mkjvf -cm -cp -expert expgothb-v hgothb-v cidjgothb
./mkjvf -expert expmgothr-h hmgothr-h cidjmgothr
./mkjvf -cm -cp -expert expmgothr-v hmgothr-v cidjmgothr
./mkjvf -ruby rubyminr-h hminr-h cidjminr
./mkjvf -cm -cp -ruby rubyminr-v hminr-v cidjminr
./mkjvf -ruby rubygothr-h hgothr-h cidjgothr
./mkjvf -cm -cp -ruby rubygothr-v hgothr-v cidjgothr
./mkjvf -ruby rubyminb-h hminb-h cidjminb
./mkjvf -cm -cp -ruby rubyminb-v hminb-v cidjminb
./mkjvf -ruby rubygothb-h hgothb-h cidjgothb
./mkjvf -cm -cp -ruby rubygothb-v hgothb-v cidjgothb
./mkjvf -ruby rubymgothr-h hmgothr-h cidjmgothr
./mkjvf -cm -cp -ruby rubymgothr-v hmgothr-v cidjmgothr
./mkjvf -expert expminl-h hminl-h cidjminl
./mkjvf -cm -cp -expert expminl-v hminl-v cidjminl
./mkjvf -ruby rubyminl-h hminl-h cidjminl
./mkjvf -cm -cp -ruby rubyminl-v hminl-v cidjminl
./mkjvf -expert expgotheb-h hgotheb-h cidjgotheb
./mkjvf -cm -cp -expert expgotheb-v hgotheb-v cidjgotheb
./mkjvf -ruby rubygotheb-h hgotheb-h cidjgotheb
./mkjvf -cm -cp -ruby rubygotheb-v hgotheb-v cidjgotheb
echo "making proportional kana tfm/vf"
perl script/mkpkana.pl
ppltotf -kanji=euc pl/phiraminw6-h.pl tfm/phiraminw6-h.tfm
ppltotf -kanji=euc pl/phirakakuw3-h.pl tfm/phirakakuw3-h.tfm
ppltotf -kanji=euc pl/phiraminw3-h.pl tfm/phiraminw3-h.tfm
ppltotf -kanji=euc pl/phiramaruw4-h.pl tfm/phiramaruw4-h.tfm
ppltotf -kanji=euc pl/phirakakuw6-h.pl tfm/phirakakuw6-h.tfm
ovp2ovf ovp/phirakakuw3-h.ovp vf/phirakakuw3-h.vf vf/phirakakuw3-h.ofm
ovp2ovf ovp/phiraminw6-h.ovp vf/phiraminw6-h.vf vf/phiraminw6-h.ofm
ovp2ovf ovp/phiraminw3-h.ovp vf/phiraminw3-h.vf vf/phiraminw3-h.ofm
ovp2ovf ovp/phirakakuw6-h.ovp vf/phirakakuw6-h.vf vf/phirakakuw6-h.ofm
ovp2ovf ovp/phiramaruw4-h.ovp vf/phiramaruw4-h.vf vf/phiramaruw4-h.ofm
perl script/mkvpkana.pl
ppltotf -kanji=euc pl/phiraminw6-v.pl tfm/phiraminw6-v.tfm
ppltotf -kanji=euc pl/phirakakuw3-v.pl tfm/phirakakuw3-v.tfm
ppltotf -kanji=euc pl/phiraminw3-v.pl tfm/phiraminw3-v.tfm
ppltotf -kanji=euc pl/phiramaruw4-v.pl tfm/phiramaruw4-v.tfm
ppltotf -kanji=euc pl/phirakakuw6-v.pl tfm/phirakakuw6-v.tfm
ovp2ovf ovp/phirakakuw3-v.ovp vf/phirakakuw3-v.vf vf/phirakakuw3-v.ofm
ovp2ovf ovp/phiraminw6-v.ovp vf/phiraminw6-v.vf vf/phiraminw6-v.ofm
ovp2ovf ovp/phiraminw3-v.ovp vf/phiraminw3-v.vf vf/phiraminw3-v.ofm
ovp2ovf ovp/phirakakuw6-v.ovp vf/phirakakuw6-v.vf vf/phirakakuw6-v.ofm
ovp2ovf ovp/phiramaruw4-v.ovp vf/phiramaruw4-v.vf vf/phiramaruw4-v.ofm
#cp hminr-h.tfm tfm/hiramin-w3-h.tfm
#cp hminr-h.tfm tfm/hiramin-w6-h.tfm
#cp hminr-h.tfm tfm/hirakaku-w3-h.tfm
#cp hminr-h.tfm tfm/hirakaku-w6-h.tfm
#cp hminr-h.tfm tfm/hiramaru-w4-h.tfm
#cp hminr-v.tfm tfm/hiramin-w3-v.tfm
#cp hminr-v.tfm tfm/hiramin-w6-v.tfm
#cp hminr-v.tfm tfm/hirakaku-w3-v.tfm
#cp hminr-v.tfm tfm/hirakaku-w6-v.tfm
#cp hminr-v.tfm tfm/hiramaru-w4-v.tfm
#echo "making ofm file for dvipdfmx in CVS"
#perl script/mkcidofm.pl
#perl script/mkpropofm.pl
echo "making tfm file with correct widths"
perl script/mkcidtfm.pl
perl script/mkproptfm.pl
#burasage
echo "making tfm/vf for burasage ..."
ppltotf basepl/brsg-h.pl tfm/brsgnmlminr-h.tfm
ppltotf basepl/brsg-v.pl tfm/brsgnmlminr-v.tfm
ppltotf basepl/brsg-h.pl tfm/brsgnmlgothr-h.tfm
ppltotf basepl/brsg-v.pl tfm/brsgnmlgothr-v.tfm
ppltotf basepl/brsg-h.pl tfm/brsgnmlminb-h.tfm
ppltotf basepl/brsg-v.pl tfm/brsgnmlminb-v.tfm
ppltotf basepl/brsg-h.pl tfm/brsgnmlgothb-h.tfm
ppltotf basepl/brsg-v.pl tfm/brsgnmlgothb-v.tfm
ppltotf basepl/brsg-h.pl tfm/brsgnmlmgothr-h.tfm
ppltotf basepl/brsg-v.pl tfm/brsgnmlmgothr-v.tfm
ppltotf basepl/brsg-h.pl tfm/brsgexpminr-h.tfm
ppltotf basepl/brsg-v.pl tfm/brsgexpminr-v.tfm
ppltotf basepl/brsg-h.pl tfm/brsgexpgothr-h.tfm
ppltotf basepl/brsg-v.pl tfm/brsgexpgothr-v.tfm
ppltotf basepl/brsg-h.pl tfm/brsgexpminb-h.tfm
ppltotf basepl/brsg-v.pl tfm/brsgexpminb-v.tfm
ppltotf basepl/brsg-h.pl tfm/brsgexpgothb-h.tfm
ppltotf basepl/brsg-v.pl tfm/brsgexpgothb-v.tfm
ppltotf basepl/brsg-h.pl tfm/brsgexpmgothr-h.tfm
ppltotf basepl/brsg-v.pl tfm/brsgexpmgothr-v.tfm
ppltotf basepl/brsg-h.pl tfm/brsgnmlgotheb-h.tfm
ppltotf basepl/brsg-v.pl tfm/brsgnmlgotheb-v.tfm
ppltotf basepl/brsg-h.pl tfm/brsgexpgotheb-h.tfm
ppltotf basepl/brsg-v.pl tfm/brsgexpgotheb-v.tfm
ppltotf basepl/brsg-h.pl tfm/brsgnmlminl-h.tfm
ppltotf basepl/brsg-v.pl tfm/brsgnmlminl-v.tfm
ppltotf basepl/brsg-h.pl tfm/brsgexpminl-h.tfm
ppltotf basepl/brsg-v.pl tfm/brsgexpminl-v.tfm
./mkjvf -sage brsgnmlminr-h hminr-h
./mkjvf -sage -cm -cp brsgnmlminr-v hminr-v
./mkjvf -sage brsgnmlgothr-h hgothr-h
./mkjvf -sage -cm -cp brsgnmlgothr-v hgothr-v
./mkjvf -sage brsgnmlminb-h hminb-h
./mkjvf -sage -cm -cp brsgnmlminb-v hminb-v
./mkjvf -sage brsgnmlgothb-h hgothb-h
./mkjvf -sage -cm -cp brsgnmlgothb-v hgothb-v
./mkjvf -sage brsgnmlmgothr-h hmgothr-h
./mkjvf -sage -cm -cp brsgnmlmgothr-v hmgothr-v
./mkjvf -sage brsgnmlgotheb-h hgotheb-h
./mkjvf -sage -cm -cp brsgnmlgotheb-v hgotheb-v
./mkjvf -sage brsgnmlminl-h hminl-h
./mkjvf -sage -cm -cp brsgnmlminl-v hminl-v
./mkjvf -sage -expert brsgexpminr-h hminr-h cidjminr
./mkjvf -sage -cm -cp -expert brsgexpminr-v hminr-v cidjminr
./mkjvf -sage -expert brsgexpgothr-h hgothr-h cidjgothr
./mkjvf -sage -cm -cp -expert brsgexpgothr-v hgothr-v cidjgothr
./mkjvf -sage -expert brsgexpminb-h hminb-h cidjminb
./mkjvf -sage -cm -cp -expert brsgexpminb-v hminb-v cidjminb
./mkjvf -sage -expert brsgexpgothb-h hgothb-h cidjgothb
./mkjvf -sage -cm -cp -expert brsgexpgothb-v hgothb-v cidjgothb
./mkjvf -sage -expert brsgexpmgothr-h hmgothr-h cidjmgothr
./mkjvf -sage -cm -cp -expert brsgexpmgothr-v hmgothr-v cidjmgothr
./mkjvf -sage -expert brsgexpgotheb-h hgotheb-h cidjgotheb
./mkjvf -sage -cm -cp -expert brsgexpgotheb-v hgotheb-v cidjgotheb
./mkjvf -sage -expert brsgexpminl-h hminl-h cidjminl
./mkjvf -sage -cm -cp -expert brsgexpminl-v hminl-v cidjminl
echo "making tfm/vf for UTF jp04 (wait a while)..."
perl script/mkjp04tfmvf.pl
echo "making tfm for jp04 ..."
ppltotf basepl/base-h.pl tfm/nmlminrn-h.tfm
ppltotf basepl/base-v.pl tfm/nmlminrn-v.tfm
ppltotf basepl/base-h.pl tfm/nmlgothrn-h.tfm
ppltotf basepl/base-v.pl tfm/nmlgothrn-v.tfm
ppltotf basepl/base-h.pl tfm/nmlminbn-h.tfm
ppltotf basepl/base-v.pl tfm/nmlminbn-v.tfm
ppltotf basepl/base-h.pl tfm/nmlgothbn-h.tfm
ppltotf basepl/base-v.pl tfm/nmlgothbn-v.tfm
ppltotf basepl/base-h.pl tfm/nmlmgothrn-h.tfm
ppltotf basepl/base-v.pl tfm/nmlmgothrn-v.tfm
ppltotf basepl/base-h.pl tfm/expminrn-h.tfm
ppltotf basepl/base-v.pl tfm/expminrn-v.tfm
ppltotf basepl/base-h.pl tfm/expgothrn-h.tfm
ppltotf basepl/base-v.pl tfm/expgothrn-v.tfm
ppltotf basepl/base-h.pl tfm/expminbn-h.tfm
ppltotf basepl/base-v.pl tfm/expminbn-v.tfm
ppltotf basepl/base-h.pl tfm/expgothbn-h.tfm
ppltotf basepl/base-v.pl tfm/expgothbn-v.tfm
ppltotf basepl/base-h.pl tfm/expmgothrn-h.tfm
ppltotf basepl/base-v.pl tfm/expmgothrn-v.tfm
ppltotf basepl/base-h.pl tfm/nmlminln-h.tfm
ppltotf basepl/base-v.pl tfm/nmlminln-v.tfm
ppltotf basepl/base-h.pl tfm/expminln-h.tfm
ppltotf basepl/base-v.pl tfm/expminln-v.tfm
ppltotf basepl/base-h.pl tfm/nmlgothebn-h.tfm
ppltotf basepl/base-v.pl tfm/nmlgothebn-v.tfm
ppltotf basepl/base-h.pl tfm/expgothebn-h.tfm
ppltotf basepl/base-v.pl tfm/expgothebn-v.tfm
ppltotf basepl/brsg-h.pl tfm/brsgnmlminrn-h.tfm
ppltotf basepl/brsg-v.pl tfm/brsgnmlminrn-v.tfm
ppltotf basepl/brsg-h.pl tfm/brsgnmlgothrn-h.tfm
ppltotf basepl/brsg-v.pl tfm/brsgnmlgothrn-v.tfm
ppltotf basepl/brsg-h.pl tfm/brsgnmlminbn-h.tfm
ppltotf basepl/brsg-v.pl tfm/brsgnmlminbn-v.tfm
ppltotf basepl/brsg-h.pl tfm/brsgnmlgothbn-h.tfm
ppltotf basepl/brsg-v.pl tfm/brsgnmlgothbn-v.tfm
ppltotf basepl/brsg-h.pl tfm/brsgnmlmgothrn-h.tfm
ppltotf basepl/brsg-v.pl tfm/brsgnmlmgothrn-v.tfm
ppltotf basepl/brsg-h.pl tfm/brsgexpminrn-h.tfm
ppltotf basepl/brsg-v.pl tfm/brsgexpminrn-v.tfm
ppltotf basepl/brsg-h.pl tfm/brsgexpgothrn-h.tfm
ppltotf basepl/brsg-v.pl tfm/brsgexpgothrn-v.tfm
ppltotf basepl/brsg-h.pl tfm/brsgexpminbn-h.tfm
ppltotf basepl/brsg-v.pl tfm/brsgexpminbn-v.tfm
ppltotf basepl/brsg-h.pl tfm/brsgexpgothbn-h.tfm
ppltotf basepl/brsg-v.pl tfm/brsgexpgothbn-v.tfm
ppltotf basepl/brsg-h.pl tfm/brsgexpmgothrn-h.tfm
ppltotf basepl/brsg-v.pl tfm/brsgexpmgothrn-v.tfm
ppltotf basepl/brsg-h.pl tfm/brsgnmlminln-h.tfm
ppltotf basepl/brsg-v.pl tfm/brsgnmlminln-v.tfm
ppltotf basepl/brsg-h.pl tfm/brsgexpminln-h.tfm
ppltotf basepl/brsg-v.pl tfm/brsgexpminln-v.tfm
ppltotf basepl/brsg-h.pl tfm/brsgnmlgothebn-h.tfm
ppltotf basepl/brsg-v.pl tfm/brsgnmlgothebn-v.tfm
ppltotf basepl/brsg-h.pl tfm/brsgexpgothebn-h.tfm
ppltotf basepl/brsg-v.pl tfm/brsgexpgothebn-v.tfm
echo "making jvf for jp04 ..."
./mkjvf -jp04 nmlminrn-h hminrn-h
./mkjvf -jp04 -cm -cp nmlminrn-v hminrn-v
./mkjvf -jp04 nmlgothrn-h hgothrn-h
./mkjvf -jp04 -cm -cp nmlgothrn-v hgothrn-v
./mkjvf -jp04 nmlminbn-h hminbn-h
./mkjvf -jp04 -cm -cp nmlminbn-v hminbn-v
./mkjvf -jp04 nmlgothbn-h hgothbn-h
./mkjvf -jp04 -cm -cp nmlgothbn-v hgothbn-v
./mkjvf -jp04 nmlmgothrn-h hmgothrn-h
./mkjvf -jp04 -cm -cp nmlmgothrn-v hmgothrn-v
./mkjvf -jp04 nmlminln-h hminln-h
./mkjvf -jp04 -cm -cp nmlminln-v hminln-v
./mkjvf -jp04 nmlgothebn-h hgothebn-h
./mkjvf -jp04 -cm -cp nmlgothebn-v hgothebn-v
./mkjvf -jp04 -expert expminrn-h hminrn-h cidjminr
./mkjvf -jp04 -cm -cp -expert expminrn-v hminrn-v cidjminr
./mkjvf -jp04 -expert expgothrn-h hgothrn-h cidjgothr
./mkjvf -jp04 -cm -cp -expert expgothrn-v hgothrn-v cidjgothr
./mkjvf -jp04 -expert expminbn-h hminbn-h cidjminb
./mkjvf -jp04 -cm -cp -expert expminbn-v hminbn-v cidjminb
./mkjvf -jp04 -expert expgothbn-h hgothbn-h cidjgothb
./mkjvf -jp04 -cm -cp -expert expgothbn-v hgothbn-v cidjgothb
./mkjvf -jp04 -expert expmgothrn-h hmgothrn-h cidjmgothr
./mkjvf -jp04 -cm -cp -expert expmgothrn-v hmgothrn-v cidjmgothr
./mkjvf -jp04 -expert expgothebn-h hgothebn-h cidjgotheb
./mkjvf -jp04 -cm -cp -expert expgothebn-v hgothebn-v cidjgotheb
./mkjvf -jp04 -expert expminln-h hminln-h cidjminl
./mkjvf -jp04 -cm -cp -expert expminln-v hminln-v cidjminl
./mkjvf -jp04 -sage brsgnmlminrn-h hminrn-h
./mkjvf -jp04 -sage -cm -cp brsgnmlminrn-v hminrn-v
./mkjvf -jp04 -sage brsgnmlgothrn-h hgothrn-h
./mkjvf -jp04 -sage -cm -cp brsgnmlgothrn-v hgothrn-v
./mkjvf -jp04 -sage brsgnmlminbn-h hminbn-h
./mkjvf -jp04 -sage -cm -cp brsgnmlminbn-v hminbn-v
./mkjvf -jp04 -sage brsgnmlgothbn-h hgothbn-h
./mkjvf -jp04 -sage -cm -cp brsgnmlgothbn-v hgothbn-v
./mkjvf -jp04 -sage brsgnmlmgothrn-h hmgothrn-h
./mkjvf -jp04 -sage -cm -cp brsgnmlmgothrn-v hmgothrn-v
./mkjvf -jp04 -sage brsgnmlgothebn-h hgothebn-h
./mkjvf -jp04 -sage -cm -cp brsgnmlgothebn-v hgothebn-v
./mkjvf -jp04 -sage brsgnmlminln-h hminln-h
./mkjvf -jp04 -sage -cm -cp brsgnmlminln-v hminln-v
./mkjvf -jp04 -sage -expert brsgexpminrn-h hminrn-h cidjminr
./mkjvf -jp04 -sage -cm -cp -expert brsgexpminrn-v hminrn-v cidjminr
./mkjvf -jp04 -sage -expert brsgexpgothrn-h hgothrn-h cidjgothr
./mkjvf -jp04 -sage -cm -cp -expert brsgexpgothrn-v hgothrn-v cidjgothr
./mkjvf -jp04 -sage -expert brsgexpminbn-h hminbn-h cidjminb
./mkjvf -jp04 -sage -cm -cp -expert brsgexpminbn-v hminbn-v cidjminb
./mkjvf -jp04 -sage -expert brsgexpgothbn-h hgothbn-h cidjgothb
./mkjvf -jp04 -sage -cm -cp -expert brsgexpgothbn-v hgothbn-v cidjgothb
./mkjvf -jp04 -sage -expert brsgexpmgothrn-h hmgothrn-h cidjmgothr
./mkjvf -jp04 -sage -cm -cp -expert brsgexpmgothrn-v hmgothrn-v cidjmgothr
./mkjvf -jp04 -sage -expert brsgexpgothebn-h hgothebn-h cidjgotheb
./mkjvf -jp04 -sage -cm -cp -expert brsgexpgothebn-v hgothebn-v cidjgotheb
./mkjvf -jp04 -sage -expert brsgexpminln-h hminln-h cidjminl
./mkjvf -jp04 -sage -cm -cp -expert brsgexpminln-v hminln-v cidjminl
echo "finishing ..."
mv *.vf vf/
mv *.tfm tfm/
rm vf/*.ofm
rm -rf ovp
rm -rf pl
rm -rf opl
